DELIMITER //
CREATE PROCEDURE dbAuth()
BEGIN
CREATE TABLE IF NOT EXISTS Users(
    id INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nom VARCHAR(255),
    prenom VARCHAR(255),
    email VARCHAR(255) UNIQUE KEY NOT NULL,
    pswd VARCHAR(255) NOT NULL
);
END//
DELIMITER ; 